#!/usr/bin/env bash
# (6) RBAC so the Ray workers can drive sandboxes.
#
# Two kinds of "pods talking to each other":
#   * NETWORK (pod -> pod IP / cluster DNS): automatic on a VPC-native cluster.
#     Nothing to configure, no tokens. This is the "direct pod-to-pod" path.
#   * CONTROL PLANE (create/delete a Sandbox CR, `kubectl exec` into its pod):
#     these go through the Kubernetes API server and therefore REQUIRE an
#     identity + RBAC. That identity is the Ray workers' ServiceAccount; its
#     auto-mounted projected token ("service token") is the credential.
#
# Design (least privilege, asymmetric):
#   * ${SANDBOX_RUNNER_SA} (used by Ray workers): may CRUD Sandboxes + exec.
#   * sandbox pods themselves: NO permissions and NO mounted token
#     (automountServiceAccountToken: false in the Sandbox spec) — untrusted
#     model-generated code must never hold an API credential.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/load-config.sh"
source "${SCRIPT_DIR}/lib.sh"

require_cmd kubectl

gen="${SCRIPT_DIR}/manifests/rbac.generated.yaml"
log "Rendering RBAC to ${gen} ..."
cat > "$gen" <<YAML
# GENERATED by 05-setup-rbac.sh from .env — edit .env, not this file.
apiVersion: v1
kind: Namespace
metadata:
  name: ${RAY_NAMESPACE}
---
apiVersion: v1
kind: Namespace
metadata:
  name: ${SANDBOX_NAMESPACE}
---
# The identity the Ray workers run as (they set serviceAccountName to this).
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${SANDBOX_RUNNER_SA}
  namespace: ${RAY_NAMESPACE}
---
# Powers, scoped to the sandbox namespace only.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sandbox-runner
  namespace: ${SANDBOX_NAMESPACE}
rules:
# Lifecycle of cold Sandbox custom resources (mini-swe backend: raw per-instance Sandbox CRs).
- apiGroups: ["agents.x-k8s.io"]
  resources: ["sandboxes"]
  verbs: ["create", "get", "list", "watch", "delete"]
# SDK warm-pool path (multiplication backend): SandboxClient.create_sandbox(warmpool=...) writes a
# SandboxClaim (and delete_sandbox deletes it) in the EXTENSIONS API group, and reads the referenced
# pool/template. Without these the SDK path 403s on sandboxclaims. (The mini-swe backend doesn't need
# them — it POSTs raw Sandbox CRs in the core group above.)
- apiGroups: ["extensions.agents.x-k8s.io"]
  resources: ["sandboxclaims"]
  verbs: ["create", "get", "list", "watch", "delete"]
# agent-sandbox-rl fleet path (mini_swe_agent_2 backend): the fleet CREATES a SandboxTemplate +
# SandboxWarmPool per SWE-bench image and deletes them at teardown (the SDK path above only READ a
# pre-applied pool/template, hence the old read-only rule).
- apiGroups: ["extensions.agents.x-k8s.io"]
  resources: ["sandboxwarmpools", "sandboxtemplates"]
  verbs: ["create", "get", "list", "watch", "delete"]
# Fleet preflight reads the target namespace (warn-only check; a namespaced Role can grant get on
# the namespace object itself).
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get"]
# Read pod state (wait for Ready before exec) ...
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
# ... and run commands inside them. 'exec' = CREATE on the pods/exec subresource.
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create", "get"]
# Optional: stream logs for debugging.
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
---
# Bind the SA (in ${RAY_NAMESPACE}) to the Role (in ${SANDBOX_NAMESPACE}).
# A RoleBinding lives in the resource namespace; the subject may be cross-namespace.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sandbox-runner
  namespace: ${SANDBOX_NAMESPACE}
subjects:
- kind: ServiceAccount
  name: ${SANDBOX_RUNNER_SA}
  namespace: ${RAY_NAMESPACE}
roleRef:
  kind: Role
  name: sandbox-runner
  apiGroup: rbac.authorization.k8s.io
---
# Cluster-scoped READ-ONLY bits for the agent-sandbox-rl fleet (mini_swe_agent_2 backend). Its
# preflight HARD-FAILS without: CRD version discovery (are the v1beta1 extensions served?) and the
# gVisor RuntimeClass check. Nodes read only feeds the best-effort RunReport environment block.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sandbox-runner-cluster-read
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get"]
- apiGroups: ["node.k8s.io"]
  resources: ["runtimeclasses"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sandbox-runner-cluster-read
subjects:
- kind: ServiceAccount
  name: ${SANDBOX_RUNNER_SA}
  namespace: ${RAY_NAMESPACE}
roleRef:
  kind: ClusterRole
  name: sandbox-runner-cluster-read
  apiGroup: rbac.authorization.k8s.io
---
# Warn-only fleet preflight check: is the agent-sandbox controller Deployment ready? Grant the one
# read it needs so in-pod runs stay warning-free (scoped to that single deployment).
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sandbox-runner-controller-read
  namespace: agent-sandbox-system
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  resourceNames: ["agent-sandbox-controller"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sandbox-runner-controller-read
  namespace: agent-sandbox-system
subjects:
- kind: ServiceAccount
  name: ${SANDBOX_RUNNER_SA}
  namespace: ${RAY_NAMESPACE}
roleRef:
  kind: Role
  name: sandbox-runner-controller-read
  apiGroup: rbac.authorization.k8s.io
YAML

log "Applying RBAC..."
kubectl apply -f "$gen"

echo
ok "RBAC applied. Verifying with 'kubectl auth can-i --as=...':"
subj="system:serviceaccount:${RAY_NAMESPACE}:${SANDBOX_RUNNER_SA}"
kubectl auth can-i create sandboxes.agents.x-k8s.io --as="$subj" -n "$SANDBOX_NAMESPACE" \
  && ok "  can create Sandboxes" || warn "  CANNOT create Sandboxes (is the CRD installed? run 04 first)"
kubectl auth can-i create pods --subresource=exec --as="$subj" -n "$SANDBOX_NAMESPACE" \
  && ok "  can exec into pods" || warn "  CANNOT exec into pods"
kubectl auth can-i delete sandboxes.agents.x-k8s.io --as="$subj" -n "$SANDBOX_NAMESPACE" \
  && ok "  can delete Sandboxes" || warn "  CANNOT delete Sandboxes"
kubectl auth can-i create sandboxclaims.extensions.agents.x-k8s.io --as="$subj" -n "$SANDBOX_NAMESPACE" \
  && ok "  can create SandboxClaims (SDK warm-pool path)" || warn "  CANNOT create SandboxClaims (multiplication SDK path will 403)"
kubectl auth can-i create sandboxwarmpools.extensions.agents.x-k8s.io --as="$subj" -n "$SANDBOX_NAMESPACE" \
  && ok "  can create SandboxWarmPools (mini_swe_agent_2 fleet path)" || warn "  CANNOT create SandboxWarmPools (mini_swe_agent_2 fleet will 403)"
kubectl auth can-i get customresourcedefinitions.apiextensions.k8s.io --as="$subj" \
  && ok "  can read CRDs (fleet preflight)" || warn "  CANNOT read CRDs (mini_swe_agent_2 fleet preflight will fail)"
kubectl auth can-i get runtimeclasses.node.k8s.io --as="$subj" \
  && ok "  can read RuntimeClasses (fleet preflight, gVisor check)" || warn "  CANNOT read RuntimeClasses (fleet preflight will fail when runtime_class is set)"
# Negative check: the runner must NOT have cluster-wide power.
if kubectl auth can-i create pods --subresource=exec --as="$subj" -n kube-system >/dev/null 2>&1; then
  warn "  runner can exec in kube-system — RBAC is too broad (expected: no)."
else
  ok "  correctly DENIED exec in kube-system (least privilege holds)"
fi

echo
log "Point your Ray pods at this identity with:  serviceAccountName: ${SANDBOX_RUNNER_SA}  (in namespace ${RAY_NAMESPACE})"
